---
title: "Constituyentes Sintácticos"
author: "Erwin Lares"
date: "10/9/2021"
output:
  bookdown::pdf_document2: default
abstract: "This document is adapted from Grant Armstrong's notes for Spanish 321. It is intended to be a resource for my students of Spanish 327"
header-includes:
- \usepackage{graphicx}
- \usepackage{float}
- \usepackage{longtable}
- \usepackage{gb4e} \noautomath % for glosses.without this it won't compile!!!
- \usepackage{ragged2e}
- \usepackage{tikz-qtree} %for simple tree syntax
- \usepackage[linguistics]{forest}
- \usepackage{setspace}\doublespacing
- \usepackage{inputenc}
- \usepackage{indentfirst}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      include = TRUE, 
                      message = FALSE, 
                      warning = FALSE)

library(tidyverse)
library(kableExtra)
library(tinytex)
library(rmarkdown)
library(bookdown)
library(knitr)
```

\newpage

# Introducción 

Podemos observar que en las lenguas naturales, las palabras se combinan para formar unidades que vamos a llamar constituyentes. A continuación vamos a experimentar con los mecanismos básicos del español para crear constituyentes. 

# Definición de un constituyente

"Un constituyente es un grupo de palabras dentro de una oración que se puede $\underline{sustituir}$ por otra palabra sin perder el significado" (Armstrong 2021)

Consideremos (\ref{constituyentes-1}) abajo

```{=tex}
\singlespacing
\begin{exe} %first level (1)
    \ex\label{constituyentes-1}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{constituyentes-1-a}
        \underline{Mi computadora nueva} no funciona.
        
        \ex\label{constituyentes-1-b}
        La hija de Juan es \underline{muy traviesa}.

        
    \end{xlist} % end first embedding
\end{exe}
\doublespacing
```

El grupo de $\underline{palabras}$ $\underline{subrayadas}$ en las oraciones de (\ref{constituyentes-1}) forman constituyentes porque **se puede sustituir todo el grupo por otra palabra sin que la oración pierda el sentido original**. Como evidencia a favor de esta posición, consideremos (\ref{constituyentes-2}). 

```{=tex}
\singlespacing
\begin{exe} %first level (1)
    \ex\label{constituyentes-2}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{constituyentes-2-a}
        \underline{Mi computadora nueva} no funciona $\rightarrow$ \underline{Ésa} no funciona.
        
        \ex\label{constituyentes-2-b}
        La hija de Juan es \underline{muy traviesa} $\rightarrow$ La hija de Juan es \underline{así}.

        
    \end{xlist} % end first embedding
\end{exe}
\doublespacing
```

¿Qué palabras podemos utilizar cuando sustituimos? Depende que la _función_/_distribución_ que realiza el constituyente que queremos sustituir. Por ejemplo, en el caso de (\ref{constituyentes-1-a}), 'mi computadora nueva" es un frase nominal, pero en (\ref{constituyentes-1-b}) es un frase adjetival.

## Palabras que se suelen utilizar para pruebas de sustitución

a. Pronombres -- pueden sustituir frases nominales -- _lo_, _la_, _le_, _los_, _las_, _les_, _éste_, _éstos_, _esto_, _ésta_, _éstas_, etc.
b. Adverbios -- pueden sustituir frases adverbiales, adjetivales, o preposicionales -- _así_, _allí_, _allá_, etc.
c. Posesivos tónicos -- pueden sustituir una frase preposicional con _de_ -- _mío_, _mía_, _tuyo_, _tuya_, _suyo_, _suya_, etc.

## Alternativas para establecer que algo es un constituyente: **preguntas**

Cuando se puede reemplazar una grupo de palabras por una palabras interrogativa **y** se puede contestar la pregunta con la secuencia que se está analizando, entonces éso es evidencia a favor de tratar el grupo de palabras como un constituyente, por ejemplo consideremos (\ref{constituyentes-3})


```{=tex}

\begin{exe} %first level (1)
    \ex\label{constituyentes-3}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{constituyentes-3-a}
            ¿Qué no funciona? $\rightarrow$ Mi computadora nueva
        \ex\label{constituyentes-3-b}
            ¿Cómo es la hija de Juan? $\rightarrow$ Muy traviesa
    \end{xlist} % end first embedding
\end{exe}
\doublespacing
```

## Práctica - pruebas de constituyentes

Demuestra que las secuencias subrayadas en los siguientes ejemplos son constituyentes usando una prueba de sustitución o una prueba de sustitución por una palabra interrogativa.

```{=tex}

\begin{exe} %first level (1)
    \ex\label{constituyentes-4}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{constituyentes-4-a}
            Trabajo con \underline{mi papá}
            
        \ex\label{constituyentes-4-b}
            Trabajo \underline{en la tienda de mi papá}
            
        \ex\label{constituyentes-4-c}
            Ellos trabajan \underline{muy rápidamente}
            
        \ex\label{constituyentes-4-d}
            \underline{El vecino que vive al lado de nosotros} ganó la lotería
            
        \ex\label{constituyentes-4-e}
            Me siento \underline{muy bien}
            
        \ex\label{constituyentes-4-f}
            \underline{A las dos de la tarde} vamos a empezar.
            
    \end{xlist} % end first embedding
\end{exe}
\doublespacing
```

# La frase nominal y sus partes

Los constituyentes reciben sus etiquetas de acuerdo a sus componentes.Los que tienen distribución de nombres se llaman **Frases Nominales** (FN). Una frase nominal consiste en un nombre y otros elementos como modifican a este nombre, como adjetivo, cuantificadores y determinantes.

## FN primera pasada: Nombres solos, Nombres y Adjetivos 

Vamos a ver el primer caso, nombres solos y frases nominales modificadas por adjetivo.

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-1}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{frases-nominales-1-a}
            No veo \underline{películas nuevas}.
            \begin{forest}
                [FN [N [películas]][A [nuevas]]]
            \end{forest}
            
        \ex\label{frases-nominales-1-b}
            Comemos \underline{pan dulce} en los días festivos.
            \begin{forest}
                [FN [N [pan]][A [dulce]]]
            \end{forest}
        
        \ex\label{frases-nominales-1-c}
            Juan y yo somos \underline{viejos amigos}.
            \begin{forest}
                [FN [A [viejos]][N [amigos]]]
            \end{forest}
        
        \ex\label{frases-nominales-1-d}
            No hay \underline{dinero}.
            \begin{forest}
                [N [dinero]]
            \end{forest}
       
    \end{xlist} % end first embedding
\end{exe}
```
Terminología importante:

- **FN**: frase nominal
- **N**: nombre
- **A**: adjetivo
- **N** "projecta" su etiqueta a la FN y por tanto es el núcleo de la FN

Una característica importante que vemos aquí (y que difiere de lo que hace Hualde) es que si no hay otra palabra que modifique al nombre, no hay un FN, simplemente un N.

## FN segunda pasada: Nombres, cuantificadores y determinantes

Otra manera de crear FFNN consiste en añadir cuantificadores y determinantes. Para refrescar la memoria
- los determinantes: artículos definidos e indefinidos, demostrativos, los posesivos átonos. La etiqueta es **D**
- los cuantificadores: los números y palabras que describen cantidades como todo, mucho, bastante, ningún y poco. La etiqueta es **Cu**

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-2}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{frases-nominales-2-a}
            Salieron \underline{tres películas nuevas} ayer.
            \begin{forest}
            where n children=0{tier=word}{}
                [FN [Cu [tres]][FN [N [películas]][A [nuevas]]]]
            \end{forest}
            
        \ex\label{frases-nominales-2-b}
            no me gusta \underline{el pan dulce}.
            \begin{forest}
            where n children=0{tier=word}{}
                [FN [D [el]][FN [N [pan]][A [dulce]]]]
            \end{forest}
        
        \ex\label{frases-nominales-2-c}
            \underline{Los mejores amigos} son los que te ayudan siempre.
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [D [los]][FN [A [mejores]][N [amigos]]]]
            \end{forest}
        
        \ex\label{frases-nominales-2-d}
            No hay \underline{mucho dinero}.
            \begin{forest}
                [FN [Cu [mucho]][N [dinero]]]
            \end{forest}
       
    \end{xlist} % end first embedding
\end{exe}
```

Cuando hay más de un modificador de un nombre, habrá varias capas de la FN. Esta son las convenciones que utilizaremos.

- la ramificación es binaria (no salen más de dos ramas de una etiqueta)
- las capas intermedias son proyecciones de la etiqueta. Si la etiqueta es N, la capa intermedia será FN.
- los cuantificadores y determinantes siempre se combinan después de los adjetivos y frases preposicionales. Por convención, asumiremos que los elementos a la derecha se combinan primero con el núcleo y los de la izquierda se combinan después. 

Los siguientes ejemplos tienen múltuiples adjetivos y un determinante.

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-3}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{frases-nominales-3-a}
            Este famoso café colombiano.
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [D [Este]][FN [A [famoso]][FN [N [café]][A [colombiano]]]]]
            \end{forest}
            
        \ex\label{frases-nominales-3-b}
            Una flor amarilla pequeña.
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [D [Una]][FN [FN [N [flor]][A [amarilla]]][A [pequeña]]]]
            \end{forest}
        
        \ex\label{frases-nominales-3-c}
            La literatura medieval española.
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [D [la]][FN [FN [N [literatura]][A [medieval]]][A [española]]]]
            \end{forest}
        
    \end{xlist} % end first embedding
\end{exe}
```

Es posible tener determinantes y cuantificadores juntos en una FN

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-4}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{frases-nominales-4-a}
            ¿Dónde están \underline{esos tres gatos locos}?
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [D [esos]][FN [Cu [tres]][FN [N [gatos]][A [locos]]]]]
            \end{forest}
        
    \end{xlist} % end first embedding
\end{exe}
```

### Practica - Practica con las siguientes frases subrayadas

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-5}
    \begin{xlist} %second level (1.a) 
        
        \ex\label{frases-nominales-5-a}
            Mi hijo tiene \underline{un pequeño carro deportivo}.
        
        \ex\label{frases-nominales-5-b}
            \underline{La producción quesera americana} ha sido afectada por los cambios del libre comercio.
            
    \end{xlist} % end first embedding
\end{exe}
```

## FN tercera pasada: coordinación

Otra manera de aumentar una frade nomina (y en general cualquier otro tipo de frases) es mediante la **coordinación**. La conjunción _y_ puede formar una frase nominal compleja. Consideremos los siguientes ejemplos:

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-6}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{frases-nominales-6-a}
            Ya salieron \underline{los perros y gatos}?

            \ex\label{frases-nominales-6-b}
            Ya salieron \underline{los perros y los gatos}?

            
            \ex\label{frases-nominales-6-c}
            \underline{Juan y Pedro siempre} llegan tarde?
            
    \end{xlist} % end first embedding
\end{exe}
```

Vamos a representar la coordinación con una estructura **ternaria** (en oposición a binaria). COn esta estrcutura vamos a representar que la estructura resultante es la unión de dos partes iguales. Entonces indicaremos que la conjunción toma un elemento a la izquierda y otro a la derecha. Como los elementos son de la misma categoría sintáctica, el resultado es una frase del mismo tipo. 

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-7}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{frases-nominales-7-a}
            los perros y gatos 
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [D [los]][N [N [perros]][Conj [y]][N [gatos]]]]
            \end{forest}

            \ex\label{frases-nominales-7-b}
            los perros y los gatos 
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [FN [D [los]][N [perros]]][Conj [y]][FN [D [los]][N [perros]]]]
            \end{forest}
            
            \ex\label{frases-nominales-7-c}
            Juan y Pedro
            \begin{forest}
                where n children=0{tier=word}{}
                [N [N [Juan]][Conj [y]][FN [Pedro]]]
            \end{forest}
            

    \end{xlist} % end first embedding
\end{exe}
```

### Práctica

Practica con las siguientes frases subrayadas. Revisaremos las respuestas juntos en clase.

```{=tex}

\begin{exe} %first level (1)
    \ex\label{frases-nominales-8}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{frases-nominales-8-a}
            \underline{Mi mamá y mi papá} viven en California.

            \ex\label{frases-nominales-8-b}
            \underline{Todos los senadores y representates} van a discutir el nuevo proyecto de ley.
            
            \ex\label{frases-nominales-8-c}
            Hay \underline{perros flacos y gatos gordos} en el hotel de mascotas.

    \end{xlist} % end first embedding
\end{exe}
```

## FN cuarta pasada: los pronombres

### Los tónicos

Como sabemos hay dos tipos de pronombres: los tónicos y los clíticos. Los pronombres tónicos tienen la misma distribución de los nombres. Consecuentemente, vamos a utilizar la misma etiqueta sintáctica **N** para representar su estructura. No es muy común ver a los pronombres tónicos modificados por determinantes, cuantificadores y adjetivos, es ciertamente una posibilidad. Por ejemplo abajo en \ref{pronombres-1} vemos varios ejemplos de pronombres tónicos simples, que se etiquetarán con **N**. Es decir, yo $\rightarrow$ **N**, ti $\rightarrow$ **N**, nosotros $\rightarrow$ **N**. 

```{=tex}

\begin{exe} %first level (1)
    \ex\label{pronombres-1}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{pronombres-1-a}
            \underline{Yo} vivo en Madison.

            \ex\label{pronombres-1-b}
            Siempre hablamos bien de \underline{ti}.

            \ex\label{pronombres-1-c}
            \underline{Nosotros} somos amigos.

    \end{xlist} % end first embedding
\end{exe}
```

Vamos a representar los pronombres tónicos modificados de la siguiente manera:

```{=tex}

\begin{exe} %first level (1)
    \ex\label{pronombres-2}
    Pronombres tónicos modificados:
    \begin{xlist} %second level (1.a) 
        
            \ex\label{pronombres-2-a}
            María siempre habla de \underline{sí misma}?
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [N [sí]][A [misma]]]
            \end{forest}

            \ex\label{pronombres-2-b}
            \underline{Todos ellos} viven en Madison.
            \begin{forest}
                where n children=0{tier=word}{}
                [FN [Cu [todos]][N [ellos]]]
            \end{forest}
            
    \end{xlist} % end first embedding
\end{exe}
```

Los pronombres tónicos se pueden combinar con cualquier \underline{otro nombre o frase nominal}. A manera de práctica, intenta representar con un árbol sintáctico el grupo de palabras subrayadas en( \ref{pronombres-3}).

```{=tex}

\begin{exe} %first level (1)
    \ex\label{pronombres-3}
    Pronombres tónicos modificados:
    \begin{xlist} %second level (1.a) 
        
            \ex\label{pronombres-3-a}
            Este asunto es \underline{entre tú y yo}.

            \ex\label{pronombres-3-b}
            \underline{Todos nosotros y ustedes} vamos a la fiesta.

    \end{xlist} % end first embedding
\end{exe}
```

### Los clíticos

Los pronombres clíticos no tienen la misma distribución que los nombres o las frases nominales. Los clíticos necesitan "apoyarse" en un verbo. No pueden modificarse ni pueden formar parte de una coordinación como se muestra en el ejemplo (\ref{pronombres-4})

```{=tex}

\begin{exe} %first level (1)
    \ex\label{pronombres-4}
    Pronombres tónicos modificados:
    \begin{xlist} %second level (1.a) 
        
            \ex\label{pronombres-4-a}
            *María se misma critica (vs. María se critica a sí misma).

            \ex\label{pronombres-4-b}
            *Los y las quiero (vs Los quiero a ellos y a ellas).

    \end{xlist} % end first embedding
\end{exe}
```

Por estas razones, vamos a representar a los pronombres clíticos de manera diferente. **No** son como los otros nombres y frases nominales; tienen su propia distribución sintáctica. Para representar su comportamiento, utilizaremos la etiqueta CL y la regla (\ref{pronombres-5})

```{=tex}

\begin{exe} %first level (1)
    \ex\label{pronombres-5}
    \begin{itemize}

        \item Reciben la etiqueta CL y forman una unidad sintáctica con el núcleo verbal.
        \item Un CL puede aparecer antes o después del núcleo verbal con el cual forma una unidad.

    \end{itemize}
\end{exe}
```

# La frase preposicional 

Una frase nominal requiere un elemento que vamos a llamar su **complemento**. EL complemento es típicamente un nombre o una frase nominal que aparece a la derecha de la preposición. La combinación de una preposición y su complemento forman una frase preposicional FP. Mira los ejemplos siguiente (\ref{preposiciones-1}).

```{=tex}

\begin{exe} %first level (1)
    \ex\label{preposiciones-1}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{preposiciones-1-a}
            Trabajo \underline{en la tienda}.

            \ex\label{preposiciones-1-b}
            Juan es \underline{de Guatemala}.
            
            \ex\label{preposiciones-1-c}
            Vamos \underline{al partido}.
            
            \ex\label{preposiciones-1-b}
            Lo hicimos \underline{sin ninguna ayuda}.

    \end{xlist} % end first embedding
\end{exe}
```

### Lista de las preposiciones en español

- a, ante, bajo, con , contra, de, desde, durante, en, entre, hacia, hasta, mediante, para, por, según, sin, so, sobre, tras, versus, vía

## Representaciones arbóreas 

```{=tex}

\begin{exe} %first level (1)
    \ex\label{preposiciones-2}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{preposiciones-2-a}
            en la tienda
            \begin{forest}
                where n children=0{tier=word}{}
                [FP [P [en]][FN [D [la]][N [tienda]]]]
            \end{forest}

            \ex\label{preposiciones-2-b}
            de Guatemala
            \begin{forest}
                where n children=0{tier=word}{}
                [P [P [de]][N [Guatemala]]]
            \end{forest}
            
            \ex\label{preposiciones-2-c}
            al partido
            \begin{forest}
                where n children=0{tier=word}{}
                [FP [P [a]][FN [D [el]][N [partido]]]]
            \end{forest}
            
            \ex\label{preposiciones-2-d}
            al partido
            \begin{forest}
                where n children=0{tier=word}{}
                [FP [P [sin]][FN [Cu [ninguna]][N [ayuda]]]]
            \end{forest}
            
    \end{xlist} % end first embedding
\end{exe}
```

En general las estructuras de las FP no serás más complicadas de lo que se aprecia en (\ref{preposiciones-2}). Sin embargo, hay casos donde modificamos FFPP con adverbios en construcciones que llamamos _intensificadores de grado_ o _focalizadores_, como se muestra en el ejemplo (\ref{preposiciones-3}).

```{=tex}

\begin{exe} %first level (1)
    \ex\label{preposiciones-3}
    \begin{xlist} %second level (1.a) 
        
            \ex\label{preposiciones-3-a}
            Ese tipo es \textit{muy} del Madrid.

            \ex\label{preposiciones-3-b}
            Los estudiantes graduados están \textit{completamente} sin dinero.
            
            \ex\label{preposiciones-3-c}
            Lo que buscas está \textit{justo} sobre la mesa.
            
    \end{xlist} % end first embedding
\end{exe}
```

Los adverbios intensificadores y focalizadores cumplen, para las FP, un papel análogo al que los determinantes y los cuantificadores hacen para las FN. Aparecen a la izquierda del núcleo y tienen significados más abstractos que los complementos. 

### Lista de adverbios intensificadores y focalizadores

- Intensificadores: muy, mucho, un poco, poco, bastante, demasiado, más, menos, tan, completemente, parcialmente, extremadamente, y otros.
- Focalizadores: casi, justo, precisamente, solo, solamente 

## Práctica:

Completa el árbol sintáctico de las FP en (\ref{preposiciones-3}).